name: Copy and Replace Convex Directory

permissions : 
  contents: write

on:
  push:
    branches:
      - dev 

jobs:
  copy_and_replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: AnjaraNasoloEricka/Webcup-Training.git
        ref : dev
        path: Webcup-Training

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: AnjaraNasoloEricka/Test_Replica.git
        ref : main
        path: Test_Replica

    - name: Copy directory from source to destination
      run: cp -R Webcup-Training/convex Test_Replica/

    - name: Commit and push changes
      run: |
        cd Test_Replica
        git config user.name "AnjaraNasoloEricka"
        git config user.email "anjaranasoloericka@gmail.com"
        git add .
        git commit -m "[chore] Update directory from source repository"
        git push https://github.com/AnjaraNasoloEricka/Test_Replica.git HEAD:main
      env:
        GA_KEY_TOKEN: ${{ secrets.GA_KEY_TOKEN }}